name: Build LaTeX Resume

on:
  push:
    branches:
      - main
    paths:
      - "resume.tex"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex

      - name: Clone target repository
        run: |
          git clone https://${{ secrets.PAT }}@github.com/guptaharsh13/files.git target_repo
          cd target_repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Copy and push PDF
        run: |
          cp ../resume.pdf target_repo/
          cd target_repo
          git add resume.pdf
          git commit -m "Update resume PDF" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
